vich_uploader:
    db_driver: orm
    
    mappings:
        doctor_photos:
            uri_prefix: /uploads/doctors
            upload_destination: '%kernel.project_dir%/public/uploads/doctors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        doctor_diplomas:
            uri_prefix: /uploads/diplomas
            upload_destination: '%kernel.project_dir%/public/uploads/diplomas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
